# Generated by Django 4.2.1 on 2023-05-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choice',
            new_name='Choices',
        ),
    ]
