# Generated by Django 4.2.1 on 2023-05-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_choices_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_tex',
            new_name='choice_text',
        ),
    ]
