# Generated by Django 4.2.1 on 2023-05-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_choice_tex_choice_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_tex',
            new_name='question_text',
        ),
    ]
